
#
# Travis configuration for CSV.
#

sudo: required
language: bash

branches:
  only:
  - main

services:
  - docker

jobs:
  include:
    - dist: xenial
      arch: amd64
      env: ARCH=amd64 VERSION=2.0.1
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      arch: amd64
      env: ARCH=arm VERSION=2.0.1
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      arch: arm64
      env: ARCH=arm64 VERSION=2.0.1
      stage: build
      script: ./scripts/travis.sh
    - dist: xenial
      arch: amd64
      env:  VERSION=2.0.1
      stage: manifest
      script: ./scripts/manifest.sh
